

export interface AllProductsINT {
    id: number,
    img: string,
    name: string,
    price: number,
}

export const apiAllProducts: AllProductsINT[] = [
    {id: 1 , img: require("../images/image-accesory1.png") , name: "چای و قهوه ساز بویانت مدل Stylish Plus" , price: 12000000},
    {id: 2 , img: require("../images/image-accesory2.png") , name: "قهوه ساز اسمگ مدل DCF02CREU" , price: 20848000},
    {id: 3 , img: require("../images/image-accesory3.png") , name: "قهوه ساز سیج مدل SDC450BSS" , price: 32854000},
    {id: 4 , img: require("../images/image-accesory4.png") , name: "اسپرسو ساز نوا مدل 168" , price: 8500000},
    {id: 5 , img: require("../images/image-accesory5.png") , name: "قهوه جوش مدل 2 Cup" , price: 256895},
    {id: 6 , img: require("../images/image-coffeBeans1.png") , name: "دانه قهوه اتیوپی عربیکا شاران" , price: 465000},
    {id: 7 , img: require("../images/image-coffeBeans2.png") , name: "دانه قهوه سینگل اورجین اتیوپی گوجی دلکینی" , price: 480000},
    {id: 8 , img: require("../images/image-coffeBeans3.png") , name: "دانه قهوه عربیکا دلکینی" , price: 351000},
    {id: 9 , img: require("../images/image-coffeBeans4.png") , name: "دانه قهوه لئو قهوه ست" , price: 292000},
    {id: 10 , img: require("../images/image-coffeBeans5.png") , name: "دانه قهوه کافی کریما طلایی قهوه ست" , price: 362720},
    {id: 11 , img: require("../images/image-dripBack1.png") , name: "قهوه دمی چکه ای Samba دونیسی" , price: 140000},
    {id: 12 , img: require("../images/image-dripBack2.png") , name: "قهوه دمی چکه ای Good Evening دونیسی" , price: 110000},
    {id: 13 , img: require("../images/image-dripBack3.png") , name: "قهوه دمی چکه ای Good Evening دونیسی" , price: 126000},
    {id: 14 , img: require("../images/image-dripBack4.png") , name: "قهوه دمی هرمی تک خاستگاه کنیا پپتینا" , price: 145000},
    {id: 15 , img: require("../images/newProduct1.png") , price: 144000, name: "دانه قهوه اسپرسو جیورنو بن مانو"},
    {id: 16 , img: require("../images/newProduct2.png") , price: 128000, name: "دانه قهوه اسپرسو جیورنو بن مانو"},
    {id: 17 , img: require("../images/newProduct3.png") , price: 350000, name: "دانه قهوه اسپرسو جیورنو بن مانو"},
    {id: 18 , img: require("../images/newProduct4.png") , price: 320000, name: "دانه قهوه اسپرسو جیورنو بن مانو"},
    {id: 19 , img: require("../images/image-powders1.png") , name: "کاپوچینو جاموکا" , price: 232500},
    {id: 20 , img: require("../images/image-powders2.png") , name: "کاپوچینو رژیمی گوددی" , price: 516000},
    {id: 21 , img: require("../images/image-powders3.png") , name: "کاپوچینو مولتی کافه" , price: 284000},
    {id: 22 , img: require("../images/image-powders4.png") , name: "کاپوچینو تورابیکا" , price: 365000},
    {id: 23 , img: require("../images/image-powders5.png") , name: "کاپوچینو تاپریکا" , price: 304000},
    {id: 24 , img: require("../images/image-powders6.png") , name: "پودر قهوه عربی" , price: 232000},
    {id: 25 , img: require("../images/image-powders7.png") , name: "قهوه هسته خرما ممتاز سرمد" , price: 74000},
    {id: 26 , img: require("../images/image-powders8.png") , name: "قهوه دان لاواتزا" , price: 2336000},
    {id: 27 , img: require("../images/image-powders9.png") , name: "شکلات داغ فوری ونزکافه" , price: 99000},
    {id: 28 , img: require("../images/image-powders10.png") , name: "پودر هات چاکلت کلاسیک سی تاج" , price: 363210},
    {id: 29 , img: require("../images/image-syrups1.png") , name: "سیروپ نارگیل سی سیب" , price: 332860},
    {id: 30 , img: require("../images/image-syrups2.png") , name: "سیروپ کارامل سی سیب" , price: 332860},
    {id: 31 , img: require("../images/image-syrups3.png") , name: "سیروپ آیریش سی سیب" , price: 332860},
    {id: 32 , img: require("../images/image-syrups4.png") , name: "سیروپ توت فرنگی سی سیب" , price: 332860},
    {id: 33 , img: require("../images/image-syrups5.png") , name: "سیروپ فندق سی سیب" , price: 332861},
    {id: 34 , img: require("../images/image-syrups6.png") , name: "سیروپ وانیل بارتینی" , price: 348000},
    {id: 35, img: require("../images/image-syrups7.png") , name: "سیروپ بلوکاراسائو سی سیب" , price: 332860},
    {id: 36 , img: require("../images/image-syrups8.png") , name: "سیروپ شکلات سی سیب" , price: 332860},
    {id: 37 , img: require("../images/image-syrups9.png") , name: "سیروپ کارامل بارتینی" , price: 348000},
]